# Generated by Django 2.2.19 on 2021-04-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('order', models.IntegerField()),
                ('url', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Navbar',
                'verbose_name_plural': 'Navbar',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=512)),
                ('content', models.CharField(max_length=1024)),
                ('image', models.ImageField(upload_to='main/slider/')),
                ('url', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Slider',
            },
        ),
    ]
