# Generated by Django 2.2.19 on 2021-04-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonsBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=2048)),
                ('image', models.ImageField(upload_to='main/anons_bar/')),
                ('is_active', models.BooleanField(default=True)),
                ('url', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Anons Bar',
                'verbose_name_plural': 'Anons Bar',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1024)),
                ('image', models.ImageField(upload_to='main/section/')),
                ('logo', models.FileField(upload_to='main/section/')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Section',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('content', models.CharField(max_length=3000)),
                ('logo', models.ImageField(upload_to='main/services/')),
                ('url', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.AddField(
            model_name='slider',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
