# Generated by Django 2.2.19 on 2021-04-12 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210412_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cargo Type',
                'verbose_name_plural': 'Cargo Types',
            },
        ),
        migrations.CreateModel(
            name='CargoWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Cargo Weight',
                'verbose_name_plural': 'Cargo Weight',
            },
        ),
        migrations.CreateModel(
            name='Carriers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=3000)),
                ('image', models.ImageField(upload_to='main/carriers/')),
            ],
            options={
                'verbose_name': 'Carrier',
                'verbose_name_plural': 'Carriers',
            },
        ),
        migrations.CreateModel(
            name='SubCarriers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=3000)),
                ('image', models.ImageField(upload_to='main/subcarriers/')),
                ('url', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'SubCarrier',
                'verbose_name_plural': 'SubCarriers',
            },
        ),
        migrations.CreateModel(
            name='TruckloadType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Truckload Type',
                'verbose_name_plural': 'Truckload Types',
            },
        ),
        migrations.CreateModel(
            name='TruckType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Truck Type',
                'verbose_name_plural': 'Truck Types',
            },
        ),
        migrations.AlterField(
            model_name='anonsbar',
            name='content',
            field=models.TextField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='services',
            name='content',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='slider',
            name='content',
            field=models.TextField(max_length=1024),
        ),
        migrations.CreateModel(
            name='CarriersForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=128)),
                ('company', models.CharField(max_length=128)),
                ('pickup_date', models.DateField(default=datetime.date.today)),
                ('delivery_date', models.DateField(default=datetime.date.today)),
                ('from_city', models.CharField(max_length=128)),
                ('to_city', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=64)),
                ('comments', models.TextField(max_length=3000)),
                ('truck_type', models.ForeignKey(on_delete=True, to='main.TruckType')),
                ('truckload_type', models.ForeignKey(on_delete=True, to='main.TruckloadType')),
            ],
            options={
                'verbose_name': 'Carrier Form',
                'verbose_name_plural': 'Carriers Form',
            },
        ),
    ]
