# Generated by Django 2.2.19 on 2021-04-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_shippersform'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('content', models.TextField(max_length=4000)),
                ('subcontent', models.TextField(max_length=2048)),
                ('image', models.ImageField(upload_to='main/about_us/')),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='AboutUsSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('content', models.TextField(max_length=4000)),
                ('subcontent', models.TextField(max_length=2048)),
                ('image', models.ImageField(upload_to='main/about_us/')),
            ],
            options={
                'verbose_name': 'About Us Section',
                'verbose_name_plural': 'About Us Section',
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('image', models.ImageField(upload_to='main/about_us/')),
                ('quantity', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Statistics',
                'verbose_name_plural': 'Statistics',
            },
        ),
    ]
