# Generated by Django 2.2.19 on 2021-04-13 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210413_0510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationform',
            name='fake',
        ),
    ]
