# Generated by Django 2.2.19 on 2021-04-13 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210413_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationcategory',
            name='title',
            field=models.TextField(max_length=100, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='category',
            field=models.ForeignKey(on_delete=True, to='main.ApplicationCategory', verbose_name='Form Category'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(max_length=512, verbose_name='Title'),
        ),
    ]
