# Generated by Django 2.2.19 on 2021-04-13 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_section_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='main/about_us/'),
        ),
    ]
