# Generated by Django 2.2.19 on 2021-04-13 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210413_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(default='main/team/avatar-default.png', upload_to='main/team/'),
        ),
    ]
