# Generated by Django 2.2.19 on 2021-04-13 05:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_faq_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faq',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
