# Generated by Django 2.2.19 on 2021-04-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20210413_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='title',
            field=models.CharField(max_length=128, verbose_name='company'),
        ),
    ]
