# Generated by Django 2.2.19 on 2021-04-13 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_shippersform'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=32)),
                ('company', models.CharField(max_length=32)),
                ('pickup_date', models.DateField(default=datetime.date.today)),
                ('delivery_date', models.DateField(default=datetime.date.today)),
                ('from_city', models.CharField(max_length=64)),
                ('to_city', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=32)),
                ('comments', models.TextField(max_length=3000)),
                ('truck_type', models.ForeignKey(on_delete=True, to='main.TruckType')),
                ('truckload_type', models.ForeignKey(on_delete=True, to='main.TruckloadType')),
            ],
            options={
                'verbose_name': 'Request Quote',
                'verbose_name_plural': 'Request Quotes',
            },
        ),
    ]
