# Generated by Django 2.2.19 on 2021-04-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20210415_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonsbar',
            name='image',
            field=models.FileField(upload_to='main/anons_bar/'),
        ),
        migrations.AlterField(
            model_name='carriers',
            name='image',
            field=models.FileField(upload_to='main/carriers/'),
        ),
        migrations.AlterField(
            model_name='carriesapplication',
            name='image',
            field=models.FileField(upload_to='main/subcarriers/'),
        ),
        migrations.AlterField(
            model_name='section',
            name='image',
            field=models.FileField(upload_to='main/section/'),
        ),
    ]
