# Generated by Django 2.2.19 on 2021-04-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20210415_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carriesapplication',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
