# Generated by Django 2.2.19 on 2021-04-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20210415_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.FileField(upload_to='main/about_us/'),
        ),
        migrations.AlterField(
            model_name='aboutussection',
            name='image',
            field=models.FileField(upload_to='main/about_us/'),
        ),
        migrations.AlterField(
            model_name='insights',
            name='image',
            field=models.FileField(upload_to='main/insights/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.FileField(default='main/team/avatar-default.png', upload_to='main/team/'),
        ),
    ]
