# Generated by Django 2.2.19 on 2021-04-16 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20210415_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='facebook',
            field=models.URLField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='instagram',
            field=models.URLField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='telegram',
            field=models.URLField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='twitter',
            field=models.URLField(blank=True, max_length=32, null=True),
        ),
    ]
