# Generated by Django 2.2.19 on 2021-04-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20210416_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='facebook',
            field=models.URLField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='instagram',
            field=models.URLField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='telegram',
            field=models.URLField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='twitter',
            field=models.URLField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.FileField(upload_to='main/slider/', verbose_name='Image'),
        ),
    ]
