# Generated by Django 2.2.19 on 2021-04-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20210416_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='fax',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='footer',
            name='phone',
            field=models.CharField(max_length=18),
        ),
    ]
