# Generated by Django 2.2.19 on 2021-04-16 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20210416_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='image',
            field=models.FileField(default='main/vacancies/default.png', upload_to='main/vacancies/'),
        ),
    ]
