# Generated by Django 2.2.19 on 2021-04-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20210417_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='url',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
