# Generated by Django 2.2.19 on 2021-04-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20210417_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='facebook',
            field=models.URLField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='instagram',
            field=models.URLField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='telegram',
            field=models.URLField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='twitter',
            field=models.URLField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='facebook',
            field=models.URLField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='instagram',
            field=models.URLField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='telegram',
            field=models.URLField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='twitter',
            field=models.URLField(blank=True, max_length=64, null=True),
        ),
    ]
