# Generated by Django 2.2.19 on 2021-04-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20210419_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='url',
            field=models.SlugField(blank=True, max_length=500, null=True, verbose_name='Url'),
        ),
    ]
