# Generated by Django 2.2.19 on 2021-04-21 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20210419_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carriersform',
            name='truck_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TruckType'),
        ),
        migrations.AlterField(
            model_name='carriersform',
            name='truckload_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TruckloadType'),
        ),
        migrations.AlterField(
            model_name='requestquote',
            name='truck_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TruckType'),
        ),
        migrations.AlterField(
            model_name='requestquote',
            name='truckload_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TruckloadType'),
        ),
        migrations.AlterField(
            model_name='shippersform',
            name='cargo_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CargoType'),
        ),
        migrations.AlterField(
            model_name='shippersform',
            name='cargo_weight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CargoWeight'),
        ),
        migrations.AlterField(
            model_name='shippersform',
            name='truck_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TruckType'),
        ),
        migrations.AlterField(
            model_name='shippersform',
            name='truckload_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TruckloadType'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PaymentType'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='work_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.WorkType'),
        ),
    ]
